insert into bank_code_list (bank_name, bank_code, lm_time) values ('BRI', '002', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BCA', '014', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BNI', '009', sysdate());
--insert into bank_code_list (bank_name, bank_code, lm_time) values ('BNI SYARIAH', '009', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('MANDIRI', '008', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BRI SYARIAH', '422', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('MANDIRI SYARIAH', '451', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BJB', '110', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BTN', '200', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('DANAMON', '011', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('CIMB NIAGA', '022', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('OCBC NISP', '028', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('PERMATA', '013', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('MAYBANK ', '016', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK MAYORA', '553', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('MAYBANK INDOCORP', '947', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('PANIN', '019', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK MEGA', '426', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('ARTHA GRAHA', '037', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('THE HONGKONG & SHANGHAI B.C.', '041', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('DBS INDONESIA', '046', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('EKSPOR INDONESIA', '003', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK ARTA NIAGA KENCANA', '020', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK BUANA IND', '023', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK LIPPO', '026', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('AMERICAN EXPRESS BANK LTD', '030', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('CITIBANK', '031', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('JP. MORGAN CHASE BANK, N.A.', '032', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK OF AMERICA, N.A', '033', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('ING INDONESIA BANK', '034', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK MULTICOR TBK.', '036', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK CREDIT AGRICOLE INDOSUEZ', '039', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('THE BANGKOK BANK COMP. LTD', '040', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('THE BANK OF TOKYO MITSUBISHI UFJ LTD', '042', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK SUMITOMO MITSUI INDONESIA', '045', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK RESONA PERDANIA', '047', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK MIZUHO INDONESIA', '048', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('STANDARD CHARTERED BANK', '050', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK ABN AMRO', '052', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK KEPPEL TATLEE BUANA', '053', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK CAPITAL INDONESIA, TBK.', '054', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK BNP PARIBAS INDONESIA', '057', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK UOB INDONESIA', '058', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('KOREA EXCHANGE BANK DANAMON', '059', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('RABOBANK INTERNASIONAL INDONESIA', '060', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('ANZ PANIN BANK', '061', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('DEUTSCHE BANK AG.', '067', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK WOORI INDONESIA', '068', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK OF CHINA LIMITED', '069', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK BUMI ARTA', '076', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK EKONOMI', '087', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK ANTARDAERAH', '088', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK HAGA', '089', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK IFI', '093', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK CENTURY, TBK.', '095', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK MAYAPADA', '097', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK DKI', '111', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BPD DIY', '112', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK JATENG', '113', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK JATIM', '114', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BPD JAMBI', '115', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BPD ACEH', '116', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK SUMUT', '117', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK NAGARI', '118', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK RIAU', '119', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK SUMSEL', '120', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK LAMPUNG', '121', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BPD KALSEL', '122', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BPD KALIMANTAN BARAT', '123', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BPD KALTIM', '124', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BPD KALTENG', '125', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BPD SULSEL', '126', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK SULUT', '127', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BPD NTB', '128', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BPD BALI', '129', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK NTT', '130', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK MALUKU', '131', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BPD PAPUA', '132', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK BENGKULU', '133', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BPD SULAWESI TENGAH', '134', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK SULTRA', '135', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK NUSANTARA PARAHYANGAN', '145', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK SWADESI', '146', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK MUAMALAT', '147', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK MESTIKA', '151', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK METRO EXPRESS', '152', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK SINAR MAS', '153', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK MASPION', '157', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK HAGAKITA', '159', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK GANESHA', '161', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK WINDU KENTJANA', '162', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('HALIM INDONESIA BANK', '164', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK HARMONI INTERNATIONAL', '166', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK KESAWAN', '167', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK HIMPUNAN SAUDARA 1906, TBK', '212', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK TABUNGAN PENSIUNAN NASIONAL', '213', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK SWAGUNA', '405', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK JASA JAKARTA', '427', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK BUKOPIN', '441', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK BISNIS INTERNASIONAL', '459', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK SRI PARTHA', '466', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK JASA JAKARTA', '472', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK BINTANG MANUNGGAL', '484', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK BUMIPUTERA', '485', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK YUDHA BHAKTI', '490', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK MITRANIAGA', '491', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK AGRO NIAGA', '494', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK INDOMONEX', '498', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK ROYAL INDONESIA', '501', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK ALFINDO', '503', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK SYARIAH MEGA', '506', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK INA PERDANA', '513', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK HARFA', '517', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('PRIMA MASTER BANK', '520', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK PERSYARIKATAN INDONESIA', '521', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK AKITA', '525', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('LIMAN INTERNATIONAL BANK', '526', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('ANGLOMAS INTERNASIONAL BANK', '531', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK DIPO INTERNATIONAL', '523', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK KESEJAHTERAAN EKONOMI', '535', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK UIB', '536', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK ARTOS IND', '542', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK PURBA DANARTA', '547', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK MULTI ARTA SENTOSA', '548', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK INDEX SELINDO', '555', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK VICTORIA INTERNATIONAL', '566', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK EKSEKUTIF', '558', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('CENTRATAMA NASIONAL BANK', '559', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK FAMA INTERNASIONAL', '562', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK SINAR HARAPAN BALI', '564', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK HARDA', '567', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK FINCONESIA', '945', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK MERINCORP', '946', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK OCBC - INDONESIA', '948', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK CHINA TRUST INDONESIA', '949', sysdate());
insert into bank_code_list (bank_name, bank_code, lm_time) values ('BANK COMMONWEALTH', '950', sysdate());
